import os
import base64
import mimetypes
from pathlib import Path
from fastmcp import FastMCP

from email.message import EmailMessage

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build



# -------------------------------------------------
# CONSTANTS & PATH SETUP
# -------------------------------------------------

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]

BASE_DIR = Path(__file__).resolve().parent
CREDENTIALS_PATH = BASE_DIR / "google_credentials.json"
TOKEN_PATH = BASE_DIR / "token.json"

REPORTS_DIR = Path(__file__).resolve().parents[1] / "reports"

mcp = FastMCP(
    name="Gmail Sender",
    json_response=True
)


# -------------------------------------------------
# AUTHENTICATION
# -------------------------------------------------

def get_gmail_service():
    """
    Loads/saves OAuth tokens and returns an authenticated Gmail service.
    """

    # Load existing token if available
    creds = None
    if TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)

    # If no token or expired/invalid → run OAuth flow
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not CREDENTIALS_PATH.exists():
                raise RuntimeError(
                    f"Missing credentials file: {CREDENTIALS_PATH}\n"
                    "Download your OAuth client JSON and place it here."
                )

            flow = InstalledAppFlow.from_client_secrets_file(
                str(CREDENTIALS_PATH), SCOPES
            )

            creds = flow.run_local_server(port=0)

        # Save the token for future use
        with open(TOKEN_PATH, "w") as token_file:
            token_file.write(creds.to_json())

    # Build Gmail API client
    return build("gmail", "v1", credentials=creds)


# -------------------------------------------------
# TOOL: send_email
# -------------------------------------------------

@mcp.tool()
def send_email(to: str, subject: str, body: str, company_name: str) -> dict:
    """
    Send an email with a PDF report attachment generated by the LaTeX tool.

    PARAMETERS
    ----------
    to : str
        Recipient email address
    subject : str
        Email subject line
    body : str
        Plain text email body
    company_name : str
        Used to locate attachment:
           Tools/reports/<company_name>_report.pdf

    RETURNS (JSON)
    --------------
    {
        "success": bool,
        "message_id": str | None,
        "attachment_path": str | None,
        "error": str | None
    }
    """

    # Sanitize filename (same logic as LaTeX tool)
    safe_name = (
        company_name.strip().lower()
        .replace(" ", "_")
        .encode("ascii", "ignore")
        .decode()
    )
    safe_name = "".join(ch for ch in safe_name if ch.isalnum() or ch in "_-")

    report_path = REPORTS_DIR / f"{safe_name}_report.pdf"

    if not report_path.exists():
        return {
            "success": False,
            "message_id": None,
            "attachment_path": str(report_path),
            "error": f"Report not found at {report_path}"
        }

    try:
        service = get_gmail_service()
    except Exception as e:
        return {
            "success": False,
            "message_id": None,
            "attachment_path": None,
            "error": f"Authentication failed: {e}"
        }

    # Create email
    message = EmailMessage()
    message.set_content(body)
    message["To"] = to
    message["From"] = "me"
    message["Subject"] = subject

    # Attach the PDF
    mime_type, _ = mimetypes.guess_type(str(report_path))
    mime_type = mime_type or "application/octet-stream"
    main_type, sub_type = mime_type.split("/", 1)

    with open(report_path, "rb") as fp:
        message.add_attachment(
            fp.read(),
            maintype=main_type,
            subtype=sub_type,
            filename=report_path.name
        )

    # Encode message for Gmail API
    encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

    try:
        send_result = service.users().messages().send(
            userId="me",
            body={"raw": encoded_message}
        ).execute()

        return {
            "success": True,
            "message_id": send_result.get("id"),
            "attachment_path": str(report_path),
            "error": None
        }

    except Exception as e:
        return {
            "success": False,
            "message_id": None,
            "attachment_path": str(report_path),
            "error": str(e)
        }

# -------------------------------------------------
# TOOL: check_email_status (needed for error correction)
# -------------------------------------------------
@mcp.tool()
def check_email_status() -> dict:
    return {
        "success": False,
        "error": "check_email_status tool is not implemented."
    }



if __name__ == "__main__":
    mcp.run(transport="streamable-http", host="0.0.0.0", port=8095)

